### ISSUE TITLE
unable to make a snap

### ISSUE THREAD

**Issue by ezraholm50** [mikix/deb2snap#12]
Hey heard about your app, cool! Tried it out but with no luck. The installation goes fine, however when i try to build the snaps i get this:

```
root@server:~/deb2snap# ./deb2snap htop
./deb2snap: regel 160: dpkg-architecture: opdracht niet gevonden
```

rule 160 dpkg-architecture: command not found

```
root@server:~/deb2snap# ./deb2snap webmin
Unknown command webmin
```

OS: ubuntu server 15.10 64 bit
Target os: ubuntu snappy core 16.04 arm hf
Please shine a light on my lack of knowledge here, is this even possible to create a snap from 64bit to armhf?

Thanks for this great project!

**Comment by mikix** [comment]
deb2snap is deprecated now.  The new hotness is snapcraft.

That said, that first error ("dpkg-architecture: command not found") might be fixed by installing dpkg-dev.

**Comment by ezraholm50** [comment]
@mikix Thanks will try it out!
