### ISSUE TITLE
errors adding the PPA on Ubuntu 15.10

### ISSUE THREAD

**Issue by pixelr0** [mikix/deb2snap#3]
W: Failed to fetch http://ppa.launchpad.net/snappy-dev/beta/ubuntu/dists/wily/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/snappy-dev/beta/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by mikix** [comment]
I've updated the instructions to say that you don't need the PPA on wily.

**Comment by pixelr0** [comment]
nice, thanks, bye o/
