### ISSUE TITLE
can not parse package.yaml: missing required fields 'vendor'

### ISSUE THREAD

**Issue by nobuto-m** [mikix/deb2snap#5]
`./deb2snap -d 15.04 hello` gives an error:
```
can not parse package.yaml: missing required fields 'vendor' (from: "name: hello\nversion: 2.9-2\n\narchitecture: amd64\n\nbinaries:\n - name: bin/hello\n")
```

However the packaging guide says "vendor" is optional.
https://developer.ubuntu.com/en/snappy/guides/packaging-format-apps/
> vendor (optional)
> 
> The name and e-mail or URL for the person providing support for this package.

Not sure something wrong with `snappy build` or deb2snap needs to mark `--vendor` mandatory.

**Comment by mikix** [comment]
The developer documentation was wrong and deb2snap should have handled that more gracefully.

I got the documentation updated and deb2snap now provides a default value if none is specified (just a dumb "Unknown" value, but it avoids the error).
